language: swift
osx_image: xcode9.2
before_script:
  - swift package update
  - swift package generate-xcodeproj
script:
  - xcodebuild test -scheme FuturaNetwork-Package -enableCodeCoverage YES
after_success:
  - curl -s https://codecov.io/bash | bash
